sudo: required
services:
  - docker
env:
  global:
    - USER_NAME=saipriyanew2018
    - USER_PASSWORD=$aipriya123$

before_install:
  - docker login -u "$USER_NAME" -p "$USER_PASSWORD"
  - docker build -t firstrepo -f Dockerfile.dev .

script:
  docker login -u saipriyanew2018 -p $aipriya123$
  - docker run -e CI=true saipriyanew2018/firstrepo npm run test
